#!/bin/bash

display_link_driver_role() {
  DISPLAY_LINK_DRIVER_URL="http://www.displaylink.com/downloads/file?id=744"
  DISPLAY_LINK_DRIVER_VER="1.3.52"

  curl -Ls "$DISPLAY_LINK_DRIVER_URL" -o /usr/local/bin/displayLinkDriver.zip
  unzip /usr/local/bin/displayLinkDriver.zip -d /usr/local/bin/
  chmod 0755 /usr/local/bin/displaylink-driver-${DISPLAY_LINK_DRIVER_VER}.run
  /usr/local/bin/displaylink-driver-${DISPLAY_LINK_DRIVER_VER}.run --keep --nox11
  touch /usr/local/bin/dis-driv-inst.txt
  systemctl enable dlm.service
}
