#!/bin/bash

docker_role() {
  apt-get install -y linux-image-extra-virtual \
                     linux-image-extra-virtual-lts-$(lsb_release -cs) \
                     apt-transport-https \
                     ca-certificates \
                     python3 \
                     python3-pip \
                     python3-httplib2
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  add-apt-repository \
	     "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
	      $(lsb_release -cs) \
	      stable"
  apt-get update
  apt-get install -y docker-ce

  pip install setuptools six docker-py passlib
  rsync --chmod 644 $FILE_LOCATION/docker-default /etc/default/docker
  systemctl enable docker
}
