#!/bin/bash

os_hardening_role() {
  # Prevent core dumps
  mkdir -p /etc/security/limits.d/
  rsync --chmod 0644 $FILE_LOCATION/limits.conf /etc/security/limits.d/10.hardcore.conf

  # Login definitions
  rsync --chmod 0444 $FILE_LOCATION/login.defs /etc/login.defs
  rsync --chmod 0444 $FILE_LOCATION/51-hide-users /usr/share/lightdm/lightdm.conf.d/51-hide-users

  # Minimize access
  chmod go-w /usr/local/sbin
  chmod go-w /usr/local/bin
  chmod go-w /usr/sbin
  chmod go-w /usr/bin
  chmod go-w /sbin
  chmod go-w /bin

  chown root:shadow /etc/shadow
  chmod 0640 /etc/shadow

  chown root:root /bin/su
  chmod 0750 /bin/su

  # Configuring pam
  pam-auth-update --package
  apt-get purge -y libpam-ccreds libpam-cracklib
  apt-get install -y libpam-pwquality libpam-modules 
  apt-get purge -y libpam-passwdqc

  # Configuring profiles
  rsync --chmod 750 $FILE_LOCATION/profile.conf /etc/profile.d/pinerolo_profile.sh

  # Securing tty
  rsync --chmod 0400 $FILE_LOCATION/securetty /etc/securetty

  # Removing sticky bit from umount
  chmod a-s /bin/umount

  # Removing sticky bit from other files
#  FILES=$(find / -xdev \( -perm -4000 -o -perm -2000 \) -type f ! -path '/proc/*' -print 2>/dev/null | sed '/\/usr\/bin\/rlogin/d')
#  for i in $(echo "$FILES") ; do
#    chmod a-s $i
#  done

  # Configuring sysctl
  rsync --chmod 0440 $FILE_LOCATION/sysctl.conf /etc/sysctl.conf
  rsync --chmod 0440 $FILE_LOCATION/ufw         /etc/default/ufw
  rsync --chmod 0444 $FILE_LOCATION/host.conf   /etc/host.confg

  # Remove login shell from some system users
  USERS=$(awk -F'':'' '{ if ( $3 <= 998 ) print $1}' /etc/passwd | grep -v "^root$\|^sync$")
  for i in $(echo "$USERS") ; do
    chsh -s /usr/sbin/nologin $i
  done

  # delete rhosts-files from system | DTAG SEC Req 3.21-4
  USERS=$(awk -F: '{print $1}' /etc/passwd)
  for i in $(echo "$USERS") ; do
    rm -f ~${i}/.rhosts
  done

  # delete hosts.equiv from system | DTAG SEC Req 3.21-4
  rm -f /etc/hosts.equiv

  # removing possibly dangerous packages
  apt-get purge -y xinetd inetd ypserv telnet-server rsh-server rsync

  # Configuring modprobe
  mkdir -p /etc/modprobe.d
  rsync --chmod 0440 $FILE_LOCATION/blacklist_modules /etc/modprobe.d/blacklist_modules.conf
}
